feat: Add UpdatePolicy and UpdatePolicies APIs
casbin/Casbin.NET pull request #267
Opened 2022-06-24 15:01 UTC by sociometry

Fix: #182 

In addition, several new unit tests are also added, such as verifying return values, which Golang version seems not to cover. I've tried them with the Golang version and the results are basically the same.

2022-06-24 16:03 UTC, hsluoyz commented
@sagilio

2022-07-03 10:35 UTC, sagilio requested changes
Most changes looks good, but a bit issues need to change.

2022-07-03 10:35 UTC, sagilio commented on Casbin/Model/Assertion.cs
> +        internal void BuildIncrementalRoleLink(PolicyOperation policyOperation, IEnumerable<string> rule, params IEnumerable<string>[] newRule)
I think optional param is not clear enough, We can add a new overload like:

```csharp
internal void BuildIncrementalRoleLink(PolicyOperation policyOperation, IEnumerable<string> oldRule, IEnumerable<string>[] newRule)
```

2022-07-03 10:35 UTC, sagilio commented on Casbin/Model/Assertion.cs
> +                    return;
Should throw an excption

2022-07-03 10:35 UTC, sagilio commented on Casbin/Model/Assertion.cs
> +                List<IEnumerable<string>> rulesList = rules.ToList();
```suggestion
                var rulesList = rules as IReadOnlyList<IEnumerable<string>> ?? rules.ToList();
```

2022-07-03 10:35 UTC, sagilio commented on Casbin.UnitTest/ModelTests/ManagementApiTest.cs
> +            bool res = e.UpdatePolicy(AsList("eve", "data3", "read"), AsList("eve", "data3", "write"));
We need to add similar tests into SyncModel dir.

2022-07-14 22:34 UTC, sagilio commented on Casbin/Model/Assertion.cs
> +            PolicyOperation policyOperation, IEnumerable<string> rule, params IEnumerable<string>[] newRule)
remove `params

2022-07-16 11:43 UTC, sagilio commented on Casbin/Model/Assertion.cs
> +            PolicyOperation policyOperation, IEnumerable<string> rule, params IEnumerable<string>[] newRule)
I will fix later

2022-07-16 12:39 UTC, sagilio approved these changes
LGTM

2022-07-16 12:39 UTC, merged