test: Add 5 multi-threading test cases for ReadWritePolicyManager
casbin/Casbin.NET pull request #271
Opened 2022-07-17 04:28 UTC by sociometry

test: Add 5 multi-threading test cases for ReadWritePolicyManager

2022-07-17 04:37 UTC, hsluoyz commented
@sociometry plz fix:

![image](https://user-images.githubusercontent.com/3787410/179384138-9d83dfe0-89d2-4e88-85a0-5c350e2c00c8.png)

2022-07-18 13:00 UTC, hsluoyz commented
@sagilio

2022-07-22 20:45 UTC, sagilio requested changes
Hope to add tests without lock timeouts

2022-07-22 20:45 UTC, sagilio commented on Casbin.UnitTest/MultithreadingTests/MultithreadingTests.cs
> +        public override Task<bool> RemovePolicyAsync(string section, string policyType, IEnumerable<string> rule)
It overwrites all content, we may not yet get the error even though the base is broken, can we mock an adapter to test?

2022-09-10 16:01 UTC, sagilio commented
ReadWritePolicyManager has been removed at #282

2022-09-10 16:01 UTC, closed without merging