feat: change lazyLoadPolicy to AutoLoadPolicy.
casbin/Casbin.NET pull request #295
Opened 2022-09-19 08:50 UTC by AsakusaRinne

Change lazyLoadPolicy to AutoLoadPolicy to avoid ignore the filter when using filtered adapter. (partially solve #288 ).

Besides, it integrates the options into ```Enforcer.Options```.

2022-10-03 16:16 UTC, AsakusaRinne commented
@sagilio Plz help to have a review ヾ(≧▽≦*)o

2022-10-04 13:10 UTC, sagilio requested changes
Most LGTM

2022-10-04 13:10 UTC, sagilio commented on Casbin/Abstractions/IEnforcer.cs
> +        public interface IEnforcerOptions
Options need not be an interface

2022-10-04 13:10 UTC, sagilio commented on Casbin/Enforcer.cs
> +            public Filter FilterInLoadPolicy { get; set; } = null;
```suggestion
            public Filter AutoLoadPolicyFilter { get; set; } = null;
```

2022-10-04 13:19 UTC, hsluoyz commented
@AsakusaRinne

2022-10-10 18:18 UTC, sagilio requested changes

2022-10-10 18:18 UTC, sagilio commented on Casbin/Abstractions/IEnforcer.cs
> -        public bool AutoCleanEnforceCache { get; set; }
I think we need not to remove those property, lt may be too many beaking changes.

2022-10-14 22:55 UTC, sagilio commented
@AsakusaRinne plz check the new change request

2022-10-15 03:50 UTC, AsakusaRinne commented
ok, I'll do it today. :)

2022-10-15 13:55 UTC, AsakusaRinne commented
I've force-pushed the commit. Since the user may want to use `Option` to set all the properties, I assigned these properties which belongs to `Enforcer` to the original properties in `EnforcerOption` to enable it.

2022-10-15 20:45 UTC, sagilio approved these changes
LGTM

2022-10-15 20:45 UTC, merged