feat: Change to Microsoft.Extensions.Configuration.Ini resolution .conf
casbin/Casbin.NET pull request #332
Opened 2023-08-31 12:27 UTC by Tanyuu

Since the library can't handle newlines and comments, the ParseStringInit method processes the string first and then feeds it into ParseBuffer. in addition, since the library doesn't support net452, it retains the old parse method.

Fix: https://github.com/casbin/Casbin.NET/issues/264

2023-08-31 13:47 UTC, hsluoyz commented
@sagilio

2023-09-10 13:50 UTC, sagilio requested changes

2023-09-10 13:50 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +        private void ParseBuffer(Stream reader)
```suggestion
        private void AddStream(Stream steam)
```

2023-09-10 13:50 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +        private MemoryStream ParseStringInit(TextReader textReader)
```suggestion
        private Stream RemoveComment(Stream stream)
```
Plz try to design by this method signature, and be called from the `AddStream` method

2023-09-10 13:50 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +            ParseBuffer(ParseStringInit(new StreamReader(configFilePath)));
```suggestion
            using FileStream fileStream = File.OpenRead(filePath);
            AddStream(fileStream);
```

2023-09-10 13:50 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +            config.ParseBuffer(config.ParseStringInit(new StringReader(text)));
```suggestion
            using var memoryStream = new MemoryStream(text);
            config.AddStream(memoryStream);
```

2023-09-11 05:18 UTC, hsluoyz commented
@sagilio plz review

2023-09-15 13:46 UTC, sagilio requested changes

2023-09-15 13:46 UTC, sagilio commented on Casbin/Casbin.csproj
> +    <PackageReference Include="Microsoft.Extensions.Configuration.Ini" Version="7.0.0" />
The version is wrong, plz change the version according to the target version.

2023-09-15 13:46 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +            StreamReader streamreader = new StreamReader(stream);
```suggestion
            using var streamReader = new StreamReader(stream);
```

2023-09-15 13:46 UTC, sagilio commented on Casbin/Config/DefaultConfig.cs
> +            TextReader textReader = new StreamReader(steam);
```suggestion
            using var streamReader = new StreamReader(stream);
```

2023-09-16 12:06 UTC, sagilio approved these changes
LGTM

2023-09-16 12:08 UTC, merged