feat: support load policy from text
casbin/Casbin.NET pull request #372
Opened 2024-09-23 02:06 UTC by Taoyuesong

close #371

This issue will be new APIs at File Adapter
```
    public static FileAdapter CreateFromFile(string filePath);
    public static FileAdapter CreateFromText(string text);
```

2024-09-23 10:21 UTC, sagilio requested changes
I believe it is not suitable to provide multiple modes in the FileAdapter, but rather to provide different Adapters. You can try to use the existing FileAdapter as a base class and extend it to create File, Stream, and Text three types of Adapters.

2024-09-23 10:21 UTC, sagilio commented on Casbin.UnitTests/ModelTests/EnforcerTest.cs
> -    public void TestInitEmptyByInputStream()
Why remove this case, plz check

2024-09-30 10:24 UTC, Taoyuesong commented on Casbin.UnitTests/ModelTests/EnforcerTest.cs
> -    public void TestInitEmptyByInputStream()
It be moved to another file.

2024-10-29 12:40 UTC, sagilio approved these changes
LGTM

2024-10-29 12:40 UTC, merged